@startuml expire command
hide footbox
activate Client
participant Client order 10
participant Database order 30
participant Request order 20

    alt request == Request::DataBase
        Client -> Request++:
        participant Query as "Query::Expire"
        create Query
        Request -> Query++:
        return query:Query
    else Request::Server
        Client -> Request:
    else Request::Publisher
        Client -> Request:
    else Request::Suscriber
        Client -> Request:
    else Request::CloseClient
        Client -> Request:
    else Request::Invalid
        Client -> Request:
    end
    
    return query: Query::Expire

    Client -> Query++: exec_query(db: Database): Response

    alt Query::Expire(key, seconds)
        Query -> Database++: expire(key, seconds)
        participant Dictionary as "dictionary: HashMap" order 35
        Database -> Dictionary ++: contains_key(key)
        return contains: bool
        alt contains == true
            alt seconds < 0
                Database -> Dictionary++: remove(key)
                deactivate Dictionary
            else else
                Database -> Database: expire_time = SystemTimeNow + seconds
                participant msg_sender as "ttl_msg_sender: Sender<MessageTtl>" order 34
                Database -> msg_sender++: send(MessageTtl::Expire(KeyTtl(key, expire_time)))
                deactivate msg_sender
            end
            Database -> Query: Ok(SuccessQuery::Boolean(true))
        else else
            return Ok(SuccessQuery::Boolean(false))
        end
    end

    alt result_query == Ok(succes)
        participant Respond as "respond: Response::Valid" order 31
        create Respond
        Query -> Respond++: Response::Valid(succes_msg: &str)
        return respond
    end
    return respond
@enduml