@startuml redis
skinparam ClassAttributeIconSize 0
hide interface fields

abstract Response
abstract Request

Class Server {
    -listener: TcpListener
    -next_id: Arc<Mutex<u32>>
    +new(config_file: &str): Result<Server, String>
    + run(): ()
}

Class Client{
    -stream: TcpStream
    -database: Database
    -subscriptions: Vec<String>
    -id: u32
    -emit_request(request: String):()
    -emit_reponse(respond: String):()
    +new(stream: TcpStream, id: u32, total_clients: u64, l: &Logger): Client
    +handle_client(db: Database, c: Channels, uptime: SystemTime, conf: ServerConf): ()
}

Class Channels{
    - channels: Dictionary
    + new(): Channels
    + add_to_channel( channel: &str, sender: Sender<String>, id: u32) : ()
    + add_monitor(): Receiver<String>
    + add_logger( logger_sender: Sender<String>): ()
    + send( channel: &str, msg: &str): i32
    + send_logger( id: u32, msg: &str): ()
    + send_monitor( id: u32, msg: &str): ()
    + unsubscribe( channel: &str, id: u32): ()
    + get_channels( pattern: &str) -> Vec<String>
    + subcriptors_number( channel: &str) -> usize
}

Class Database {
    - dictionary: HashMap<String, StorageValue>
    -ttl_msg_sender: Sender<MessageTtl>
    + new(): Database
    + flushdb(): Result<SuccessQuery, DataBaseError>
    + dbsize(): Result<SuccessQuery, DataBaseError>
    + copy(key: &str, to_key: &str): Result<SuccessQuery, DataBaseError>
}

Class ServerConf {
    - conf: HashMap<String, String>
    + addr(): String
    + logfile(): String
    + get_config(): Result<SuccessQuery, DataBaseError>
    + set_config(): Result<SuccessQuery, DataBaseError>
    + get_time_out(): u64
}

Class Logger {
    - file_path: String
    - verbose: Arc<AtomicBool>
    + new(file_path: &str): Logger
    + run(): Sender<String>
    + set_verbose(new_value: bool): ()
}

abstract Class Request {
    +{abstract}new(request: &str): Request
    +{static}parse_request(stream: &mut TcpStream) -> Result<String, String>
}

abstract Class Response {
    -msg: &str
    +{abstract}respond(stream: &TcpStream)
}

Class Valid{
    +respond(stream: &mut TcpStream): ()
}

Class Error{
    +respond(stream: &mut TcpStream): ()
}


Server *-- Database
Server *-- ServerConf
Server *-- Channels
Server .up.> Logger
Server .right.> Client

Client *-- Logger
Client .up.> Request
Client o--ServerConf

Request .right.> Response

Response <|-- Valid
Response <|-- Error


@enduml
